### ISSUE TITLE
question about DeepTEN

### ISSUE THREAD

**Issue by hhyhcr449** [rgmyr/keras-texture#5]
Great job！
But I have a question about the codebook .In my understanding, dictionary learning is equal to sparse encoding, but why is the size of the codebook is （32,128）？thank you very much！

**Comment by rgmyr** [comment]
I think section 2 in the paper should answer your questions, but basically you have: 
- The codebook `C = {c_1, ... , c_K}` 
- Some set of input feature vectors `X = {x_1, ..., x_N}`

The `K*N` residual vectors are given by `r_ik = x_i - c_k`, so the feature vectors `x_i` and codewords `c_k` have to be the same size (in this case, `D`, the number of CNN output channels). And so the shape of the codebook `C` is `(K, D)`.

The output is then a weighted aggregation of residual vectors over the `N` input locations, so that you end up with an encoding vector with fixed size `K`.
